#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "bffuck",
# ]
# ///

import argparse
import os.path
import subprocess
from tabnanny import verbose
from unittest import case

from bffuck import BFFuck

from internal.common import IL, CONVERT_TABLE
from internal.optimize import optimize_il


CODE = """
#include <stdio.h>

unsigned long long tape_ptr = 0;
unsigned char BUFFER[{tape_length}] = {{0}};

#define ptr_next() tape_ptr = (tape_ptr+1)%{tape_length}
#define ptr_prev() tape_ptr = (tape_ptr-1)%{tape_length}
#define inc()      BUFFER[tape_ptr]++
#define dec()      BUFFER[tape_ptr]--
#define out()      printf("%c", (char)BUFFER[tape_ptr])
#define in()       BUFFER[tape_ptr] = (unsigned char)getchar()

// Optimized IL Commands
#define set(x)     BUFFER[tape_ptr] = x
#define add(x)     BUFFER[tape_ptr] += x
#define sub(x)     BUFFER[tape_ptr] -= x
#define skip(x)    tape_ptr = (tape_ptr+x)%{tape_length}
#define back(x)    tape_ptr = (tape_ptr-x)%{tape_length}


int main(){{
    {program_code}
}}
"""

def compile_il_to_c(bf, tape_length, emit_c):
    c_src = ""

    skipnext = False
    for c, il in enumerate(bf):
        if skipnext:
            skipnext = False
            continue

        match il:
            case IL.NEXT:
                c_src += CONVERT_TABLE[il]
            case IL.PREV:
                c_src += CONVERT_TABLE[il]
            case IL.INC:
                c_src += CONVERT_TABLE[il]
            case IL.DEC:
                c_src += CONVERT_TABLE[il]
            case IL.OUT:
                c_src += CONVERT_TABLE[il]
            case IL.IN:
                c_src += CONVERT_TABLE[il]
            case IL.LOOP:
                c_src += CONVERT_TABLE[il]
            case IL.ENDL:
                c_src += CONVERT_TABLE[il]

            case IL.SET:
                c_src += CONVERT_TABLE[il].format(operand=bf[c+1])
                skipnext = True
            case IL.ADD:
                c_src += CONVERT_TABLE[il].format(operand=bf[c+1])
                skipnext = True
            case IL.SUB:
                c_src += CONVERT_TABLE[il].format(operand=bf[c+1])
                skipnext = True
            case IL.SKIP:
                c_src += CONVERT_TABLE[il].format(operand=bf[c+1])
                skipnext = True
            case IL.BACK:
                c_src += CONVERT_TABLE[il].format(operand=bf[c+1])
                skipnext = True
            case _:
                raise ValueError("Unhandled il type")

        if emit_c:
            c_src += "\n"

    real_c_src = CODE.format(tape_length=tape_length, program_code=c_src)

    return real_c_src

def compile_c(c, output, verbose):
    subprocess.run(["gcc", "-x", "c", "-O3", "-", "-o", output if output else "a.out"], input=c.encode(), stdout=None if verbose else subprocess.DEVNULL, check=True)

# "cleans" bf code; Removing comments and whitespace
def clean_bf(bf: str) -> list[str]:
    clean = []
    for line in bf.split("\n"):
        for char in line:
            # We follow both bf standards:
            # Any char that is not valid is ignored
            # and Anything after a # is ignored
            if char == "#":
                break

            if char not in [">", "<", "+", "-", ".", ",", "[", "]"]:
                continue

            clean.append(char)
    return clean

def compile_bf_to_il(bf: list[str]):
    il = []
    for char in bf:
        match char:
            case ">":
                il.append(IL.NEXT)
            case "<":
                il.append(IL.PREV)
            case "+":
                il.append(IL.INC)
            case "-":
                il.append(IL.DEC)
            case ".":
                il.append(IL.OUT)
            case ",":
                il.append(IL.IN)
            case "[":
                il.append(IL.LOOP)
            case "]":
                il.append(IL.ENDL)
            case _:
                raise ValueError(f"Invalid Brainfuck: {char}")
    return il

def run_compiler(bf, tape_length, output, emit_c, verbose):
    if verbose:
        print("Step 1: Removing comments and whitespace...")
    bf_cleaned = clean_bf(bf)
    if verbose:
        print(f"Cleaned: {''.join(bf_cleaned)}")

        print("Step 2: Compiling to IL...")
    il: list[IL] = compile_bf_to_il(bf_cleaned)
    if verbose:
        print(f"IL: {', '.join([i.name for i in il])}")

        print("Step 3: Optimizing IL...")
    il = optimize_il(il)
    if verbose:
        str_il = []
        for i in il:
            if isinstance(i, IL):
                str_il.append(i.name)
            else:
                str_il.append(str(i))
        print(f"IL: {', '.join(str_il)}")

        print("Step 3: Compiling to C...")
    c_src = compile_il_to_c(il, tape_length, emit_c)

    if emit_c:
        print(c_src)
        return

    if verbose:
        print("Step 4: Compiling C Code...")
    compile_c(c_src, output, verbose)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("input", help="The brainfuck file to compile")
    parser.add_argument("-o", "--output", help="The output compiled file")
    parser.add_argument("-t", "--tape-length", help="The length of the number tape", type=int, default=256)
    parser.add_argument("-f", "--flavour", help="The Brainfuck flavour to use", choices=["classic", "bffuck"], default="classic")
    parser.add_argument("--emit-c", help="Emit the intermediate C code and exit", action="store_true")
    parser.add_argument("-v", "--verbose", help="Make output more verbose", action="store_true")
    args = parser.parse_args()

    if args.tape_length < 1:
        print("Invalid tape length")
        exit(1)

    if not os.path.exists(args.input):
        print(f"{args.input} does not exist")
        exit(1)

    with open(args.input, "r") as srcfile:
        src = srcfile.read()

    if args.flavour == "bffuck":
        src = BFFuck().compile(src)


    run_compiler(src, args.tape_length, args.output, args.emit_c, args.verbose)

if __name__ == "__main__":
    main()
